--- 
# config file to run a MC and LV pipeline map generator
pipemap:
  # Pipe cube generation
  - survey_type: LVM #Cube Survey Type
    out_path: out_maps/ #path of the output cube files
    redux_ver: 1.1.1.dev0 #the DRP reduction version of the lvmCFrame
    redux_dir: '' #path of the redux dir, default set to '' to set to path_sas/sdsswork/lvm/spectro/redux
    type: c #id for the kernel selection: 16-a,8-b,4-c,2-d,1-e,1/2-f,1/4-g,1/8-h,1/16-i,1/32-i, default c
    nameL: [NAME1,NAME2] #output root name of the list of targets names for the files with the tiles, mjds and expnumbers
    use_slitmap: True #flag to use the astrometry saved in the slitmap header
    pbars: True #flag to activate or deactivate the progress bar
    path_sas: '' #path to the local SDSS SAS directory, will be used this value if SAS_BASE_DIR is not defined in the environment
    basename: lvmSFrame-NAME.fits #base name of the RSS file
    fac_sizeY: 1.1 #factor of the FoV in Y
    fac_sizeX: 1.1 #factor of the FoV in X
    cent: True #activate the centering of the FoV
    coord_cenL: [[0,0],[0,0]] #central coordinates ra, dec in degrees 
    pathF: '' #path of the list of mjd, explist and tiles of the targets
    redshift: 0.0 #redshift of the target
    deconv: False #flag to activate or deactivate the deconvolution of the map
    psfdecv: 0.0 #psf in sigma for the deconvolution (in arcsec), if 0 it will set to sqrt(fib^2+kernel^2)
...